version: '3'

services:
  server:
    build: ./
    ports:
      - 5000:8080
  postgres:
    image: postgres:latest
    environment: 
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - palo-postgres:/var/lib/postgresql/data
    ports:
      - 6000:6000
    depends_on: 
      - server
  frontend:
    build: .
    entrypoint: frontend
    ports:
      - "4000:9000"
    links:
      - account
      - product
      - review
      - shop
      - user
      - ordering
      - session
      - shopping
    depends_on:
      - account
      - product
      - review
      - shop
      - user
      - ordering
      - session
      - shopping
  account:
    build: .
    entrypoint: account
    links:
      - user
  product:
    build: .
    entrypoint: product
    links:
      - review
  review:
    build: .
    entrypoint: review
  shop:
    build: .
    entrypoint: shop
    links:
      - product
      - review
  user:
    build: .
    entrypoint: user
    links:
      - ordering
      - shopping
  ordering:
    build: .
    entrypoint: ordering
    links:
      - shopping
  session:
    build: .
    entrypoint: session
    links:
      - user
  shopping:
    build: .
    entrypoint: shopping
volumes: 
  palo-postgres