version: "3.8"  
services:
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  adak:
    build: .
    restart: always
    environment:
      ADMIN_EMAILS: test@gmail.com # Replace this with the admins email (it's a slice)
      SV_HOST: 0.0.0.0 # Do not bind to 127.0.0.1 as Docker can't reach the app inside the container.
      SV_PORT: 4000
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 4000:4000
    depends_on:
      - db

  adak-api:
    build:
      context: ./api/swagger
    ports:
      - 8080:8080
    
volumes:
  postgres-data:
