version: "3.8"  
services:
  
  adak:
    build: .
    restart: always
    environment: # Check all the environment variables in .env_example, as they are required
      SV_HOST: 0.0.0.0 # Do not bind to 127.0.0.1 as Docker can't reach the app inside the container.
      SV_PORT: 4000
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 4000:4000
    depends_on:
      - postgres
    networks:
      - storage

  adak-api:
    image: gastonpalomeque/adak-api
    ports:
      - 8080:8080
  
  postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - storage

  memcached:
    image: memcached:1.6.9-alpine
    restart: on-failure:5
    ports:
      - 11211:11211
    networks:
      - storage
    
volumes:
  postgres-data:

networks:
  storage: