version: "3.8" 
services:
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  adak:
    build: .
    restart: always
    environment:
      SV_HOST: 0.0.0.0 # Do not bind to 127.0.0.1 as Docker can't reach the app inside the container.
      SV_PORT: 4000
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 4000:4000
    depends_on:
      - db
  
  frontend:
    image: adak_adak
    entrypoint: main frontend
    ports:
      - 9000:9000
    links:
      - account
      - product
      - review
      - shop
      - user
      - ordering
      - session
      - shopping
    depends_on:
      - db
      - adak
      - account
      - product
      - review
      - shop
      - user
      - ordering
      - session
      - shopping
  account:
    image: adak_adak
    entrypoint: main account
    links:
      - user
  product:
    image: adak_adak
    entrypoint: main product
    links:
      - review
  review:
    image: adak_adak
    entrypoint: main review
  shop:
    image: adak_adak
    entrypoint: main shop
    links:
      - product
      - review
  user:
    image: adak_adak
    entrypoint: main user
    links:
      - ordering
      - shopping
  ordering:
    image: adak_adak
    entrypoint: main ordering
    links:
      - shopping
  session:
    image: adak_adak
    entrypoint: main session
    links:
      - user
  shopping:
    image: adak_adak
    entrypoint: main shopping

volumes:
  postgres-data: