version: "3.8" 
services:
  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # Make sure that ./postgres-data/pg_hba.conf contains the following line to connect to postgres
      # host    all             all             0.0.0.0/0               trust

  # This service is used to build the image only, it will fail on execution but it doesn't interfere with the other service functionality
  micro_server:
    build: .
    environment:
      ADAK_CONFIG: /config.yml
    volumes:
      - ./config_micro.yml:/config.yml:ro
  
  api:
    image: adak_micro_server
    restart: on-failure:3
    entrypoint: adak api
    ports:
      - 4000:4000
    depends_on:
      - postgres
      - account
      - product
      - review
      - shop
      - user
      - ordering
      - session
      - shopping
  account:
    image: adak_micro_server
    restart: on-failure:3
    entrypoint: adak account
    expose:
      - 2727
  product:
    image: adak_micro_server
    restart: on-failure:3
    entrypoint: adak product
    expose:
      - 2727
  review:
    image: adak_micro_server
    restart: on-failure:3
    entrypoint: adak review
    expose:
      - 2727
  shop:
    image: adak_micro_server
    restart: on-failure:3
    entrypoint: adak shop
    expose:
      - 2727
  user:
    image: adak_micro_server
    restart: on-failure:3
    entrypoint: adak user
    expose:
      - 2727
  ordering:
    image: adak_micro_server
    restart: on-failure:3
    entrypoint: adak ordering
    expose:
      - 2727
  session:
    image: adak_micro_server
    restart: on-failure:3
    entrypoint: adak session
    expose:
      - 2727
  shopping:
    image: adak_micro_server
    restart: on-failure:3
    entrypoint: adak shopping
    expose:
      - 2727

volumes:
  postgres-data: