version: "3.8"  
services:
  
  server:
    build: .
    restart: on-failure:10
    environment:
      ADAK_CONFIG: /config.yml
    ports:
      - 4000:4000
    volumes: # Mount private files
      - ./config.yml:/config.yml
      - ./cmd/server/certs:/certs/
    networks:
      - storage
    depends_on:
      - postgres
      - memcached

  adak-api:
    image: gastonpalomeque/adak-api
    ports:
      - 8080:8080
  
  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: adak
      POSTGRES_PASSWORD: adak
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - storage

  memcached:
    image: memcached:1.6.9-alpine
    restart: on-failure:5
    ports:
      - 11211:11211
    networks:
      - storage
    
volumes:
  postgres-data:

networks:
  storage: