version: "3.8" 
services:
  db:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks: 
      - net
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data

  adak:
    build: .
    restart: always
    environment:
      SV_HOST: 0.0.0.0 # Do not bind to 127.0.0.1 as Docker can't reach the app inside the container.
      SV_PORT: 4000
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 4000:4000
    networks: 
      - net
    depends_on:
      - db
  
  frontend:
    image: adak_adak
    entrypoint: adak frontend
    ports:
      - 8080:8080
    networks: 
      - net
    depends_on:
      - db
      - adak
      - account
      - product
      - review
      - shop
      - user
      - ordering
      - session
      - shopping
  account:
    image: adak_adak
    entrypoint: adak account
    networks: 
      - net
  product:
    image: adak_adak
    entrypoint: adak product
    networks: 
      - net
  review:
    image: adak_adak
    entrypoint: adak review
  shop:
    image: adak_adak
    entrypoint: adak shop
    networks: 
      - net
  user:
    image: adak_adak
    entrypoint: adak user
    networks: 
      - net
  ordering:
    image: adak_adak
    entrypoint: adak ordering
    networks: 
      - net
  session:
    image: adak_adak
    entrypoint: adak session
    networks: 
      - net
  shopping:
    image: adak_adak
    entrypoint: adak shopping
    networks: 
      - net

volumes:
  postgres-data:

networks:
  net: